version: 2
jobs:
  unittests:  # Run the unit tests from the tests package.
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            python3 -m unittest discover -s tests
  pydocstyle:  # Check for code documentation style with pydocstyle
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv polynomialenv
            . polynomialenv/bin/activate
            pip3 install pydocstyle
      - run:
          name: run tests
          command: |
            . polynomialenv/bin/activate
            python3 -m pydocstyle polynomial
workflows:
  version: 2
  workflow:
    jobs:
    - unittests
    - pydocstyle
