version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            python3 -m unittest discover -s tests
  pydocstyle:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install pydocstyle
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m pydocstyle .
workflows:
  version: 2
  workflow:
    jobs:
    - test
    - pydocstyle
